//**********************************************************************
//    CopyRight  (c)  
//    File Name   :   Function.h
//    Function    :   Store quote of the function 
//    Version     :   V3.2.0
//    Date        :   2022.02.16
//**********************************************************************
#ifndef FUNCTION_H
    #define FUNCTION_H
#endif	

/**************************************Generated by EasyCodeCube*************************************/
//Forbid editing areas between the labels !!!
extern void IcResourceInit(void);
/*************************************.Generated by EasyCodeCube.************************************/
