/************************************************************
//  Copyright (c)
//  FileName	 : main.c
//  Module Function	:
//  Instructions : Contains the MCU initialization function and its H file
*******************Includes************************************************************************/
#include "SC_Init.h"
#include "SC_it.h"
#include "HeadFiles\SysFunVarDefine.h"
#include "stdio.h"
#include "Function_Init.h"
#include "sc32_conf.h"

#include "..\FWLib\TK_LIB\sc32f10xx_TK_ParameterAnalysis.h"
#include "..\FWLib\TK_LIB\sc32f10xx_TK_FunctionResource.h"
#include "..\SOC_DebugTouchKey_Lib\sc32f10xx_TK_DynamicDebug.h"

#include "lvgl.h"
#include "lv_port_disp_template.h"
#include "lv_port_indev_template.h"

#include "gui_guider.h"
#include "events_init.h"
/**************************************Generated by EasyCodeCube*************************************/
//Forbid editing areas between the labels !!!

/*************************************.Generated by EasyCodeCube.************************************/
/*****************************************************************************************************
* Function Name: main
* Description  : This function implements main function.
* Arguments    : None
* Return Value : None
******************************************************************************************************/
lv_ui guider_ui;

int main ( void )
{
    /*<Generated by EasyCodeCube begin>*/
    /*<UserCodeStart>*//*<SinOne-Tag><36>*/
    SC_Init();        //HLCK 分频为1分频
    __enable_irq(); // 开启总中断
		
   /*<Generated by EasyCodeCube begin>*/

//    QSPI_Striaight_Mode_TFT();
		TK_Init();
		lv_init();
		lv_port_disp_init();
		lv_port_indev_init();
	
		setup_ui(&guider_ui);
   	events_init(&guider_ui);
    /*****MainLoop*****/
    while ( 1 )
    {
        /*<UserCodeStart>*//*<SinOne-Tag><14>*/
        /***User program***/
//			WDT_SetReload();
			Sys_Scan();//调用TK按键函数
			lv_timer_handler();
        /*<UserCodeEnd>*//*<SinOne-Tag><14>*/
        /*<Begin-Inserted by EasyCodeCube for Condition>*/
    }
    /*<UserCodeEnd>*//*<SinOne-Tag><4>*/

    /*<Generated by EasyCodeCube end>*/

}
