/************************************************************
Copyright (c)
FileName	: SC_Init.h
Function	: Contains the MCU initialization function and its H file
Instructions        :  

******************************************************************************
* @attention
*
*1.This software is supplied by SinOne Microelectronics Co.,Ltd. and is only 
*intended for use with SinOne products. No other uses are authorized. This 
*software is owned by SinOne Microelectronics Co.,Ltd. and is protected under 
*all applicable laws, including copyright laws. 
*2.The software which is for guidance only aims at providing customers with 
*coding information regarding their products in order for them to save time. 
*As a result, SinOne shall not be held liable for any direct, indirect or 
*consequential damages with respect to any claims arising from the content of 
*such software and/or the use made by customers of the coding information 
*contained herein in connection with their products.
*
*  COPYRIGHT 2024 SinOne Microelectronics
*/
#ifndef _SC_INIT_H_
#define _SC_INIT_H_

#include "sc32_conf.h"

void SC_Init(void);
void SC_NVIC_Init(void);
void SC_SYSTICK_Init(void);
void SC_RCC_Init(void);
void SC_OPTION_Init(void);
void SC_GPIO_Init(void);
void SC_UART0_Init(void);
void SC_UART1_Init(void);
void SC_UART2_Init(void);
void SC_UART3_Init(void);
void SC_UART4_Init(void);
void SC_UART5_Init(void);
void SC_TIM0_Init(void);
void SC_TIM1_Init(void);
void SC_TIM2_Init(void);
void SC_TIM3_Init(void);
void SC_TIM4_Init(void);
void SC_TIM5_Init(void);
void SC_TIM6_Init(void);
void SC_TIM7_Init(void);
void SC_PWM0_Init(void);
void SC_LEDPWM_Init(void);
void SC_INT_Init(void);
void SC_ADC_Init(void);
void SC_OP_Init(void);
void SC_IAP_Init(void);
void SC_TWI4_Init(void);
void SC_TWI3_Init(void);
void SC_TWI1_Init(void);
void SC_TWI0_Init(void);
void SC_SPI0_Init(void);
void SC_SPI1_Init(void);
void SC_SPI3_Init(void);
void SC_SPI4_Init(void);
void SC_BTM_Init(void);
void SC_CRC_Init(void);
void SC_DMA0_Init(void);
void SC_DMA1_Init(void);
void SC_DMA3_Init(void);
void SC_DMA4_Init(void);
void SC_WDT_Init(void);
void SC_PWR_Init(void);
void SC_LCD_Init(void);
void SC_LED_Init(void);
void SC_MDU_Init(void);
void SC_ACMP_Init(void);
void SC_QSPI0_Init(void);
void SC_QSPI1_Init(void);
void SC_CAN_Init(void);
#endif

/**************************************Generated by EasyCodeCube*************************************/
//Forbid editing areas between the labels !!!
/*************************************.Generated by EasyCodeCube.************************************/
