/*****************************************************************************
 *Copyright (c)
 *FileName	  : SC_it.c
 *Function	  : Interrupt Service Routine
 *Date          :29-1-2024
 *Version       : V0.2
 ******************************************************************************
 * @attention
 *
 *1.This software is supplied by SinOne Microelectronics Co.,Ltd. and is only 
 *intended for use with SinOne products. No other uses are authorized. This 
 *software is owned by SinOne Microelectronics Co.,Ltd. and is protected under 
 *all applicable laws, including copyright laws. 
 *2.The software which is for guidance only aims at providing customers with 
 *coding information regarding their products in order for them to save time. 
 *As a result, SinOne shall not be held liable for any direct, indirect or 
 *consequential damages with respect to any claims arising from the content of 
 *such software and/or the use made by customers of the coding information 
 *contained herein in connection with their products.
 *
 *  COPYRIGHT 2024 SinOne Microelectronics
 */
/********************Includes************************************************************************/
#include "SC_it.h"
#include "sc32_conf.h"
#include "stdio.h"
#include "SC_itExtern.h"
#include "Function_Init.h"
#include "lvgl.h"

/**************************************Generated by EasyCodeCube*************************************/
//Forbid editing areas between the labels !!!

/*************************************.Generated by EasyCodeCube.************************************/

void INT0_IRQHandler(void)
{
  /*INT0_it write here begin*/
  //Forbid editing areas between the labels !!!
  /*INT0_it write here*/
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
  /*INT0Interrupt Flag Clear begin*/
  //Forbid editing areas between the labels !!!
  /*INT0Interrupt Flag Clear end*/
}

void INT1_7_IRQHandler(void)
{
  /*INT1_7_it write here begin*/
  //Forbid editing areas between the labels !!!
  /*INT1_7_it write here*/
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
  /*INT1_7Interrupt Flag Clear begin*/
  //Forbid editing areas between the labels !!!
  /*INT1_7Interrupt Flag Clear end*/
}

void INT8_11_IRQHandler(void)
{
  /*INT8_11_it write here begin*/
  //Forbid editing areas between the labels !!!
  /*INT8_11_it write here*/
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
  /*INT8_11Interrupt Flag Clear begin*/
  //Forbid editing areas between the labels !!!
  /*INT8_11Interrupt Flag Clear end*/
}

void INT12_15_IRQHandler(void)
{
  /*INT12_15_it write here begin*/
  //Forbid editing areas between the labels !!!
  /*INT12_15_it write here*/
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
  /*INT12_15Interrupt Flag Clear begin*/
  //Forbid editing areas between the labels !!!
  /*INT12_15Interrupt Flag Clear end*/
}

void RCC_IRQHandler(void)
{
  /*RCC_it write here begin*/
  //Forbid editing areas between the labels !!!
  /*RCC_it write here*/
  /*<Generated by EasyCodeCube begin>*/
  
  /*<Generated by EasyCodeCube end>*/
  /*RCCInterrupt Flag Clear begin*/
  //Forbid editing areas between the labels !!!
  /*RCCInterrupt Flag Clear end*/
}

#if !defined (TK_USE_BTM)
void BTM_IRQHandler(void)
{
  /*BTM_it write here begin*/
  //Forbid editing areas between the labels !!!
  /*BTM_it write here*/
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
  /*BTMInterrupt Flag Clear begin*/
  //Forbid editing areas between the labels !!!
  /*BTMInterrupt Flag Clear end*/
}
#endif

void UART0_2_4_IRQHandler(void)
{
  /*UART0_2_it write here begin*/
  //Forbid editing areas between the labels !!!
  /*UART0_2_it write here*/
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
  /*UART0_2Interrupt Flag Clear begin*/
  //Forbid editing areas between the labels !!!
  /*UART0_2Interrupt Flag Clear end*/
}

void UART1_3_5_IRQHandler(void)
{
  /*UART1_3_it write here begin*/
  //Forbid editing areas between the labels !!!
  /*UART1_3_it write here*/
  /*<Generated by EasyCodeCube begin>*/ 
  /*<Generated by EasyCodeCube end>*/
  /*UART1_3Interrupt Flag Clear begin*/
  //Forbid editing areas between the labels !!!
  /*UART1_3Interrupt Flag Clear end*/
}

void TWIx_QSPIx_0_2_IRQHandler(void)
{
  /*SPI0_it write here begin*/
  //Forbid editing areas between the labels !!!
  /*SPI0_it write here*/
  /*<Generated by EasyCodeCube begin>*/
  QSPIx_0_2_TFTDriver();
  /*<Generated by EasyCodeCube end>*/
  /*SPI0Interrupt Flag Clear begin*/
  //Forbid editing areas between the labels !!!
  /*SPI0Interrupt Flag Clear end*/
}

void TWIx_QSPIx_1_3_IRQHandler(void)
{
  /*SPI1_it write here begin*/
  //Forbid editing areas between the labels !!!
  /*SPI1_it write here*/
	if (READ_BIT(QSPI1->TWI_QSPIx_STS, TWI_QSPIx_STS_QTWIF)) {
        QSPI1->TWI_QSPIx_STS = 0x00000001;
        //		 SPIF_flag = 1;
        PC_OT(4);
    }

    if (READ_BIT(QSPI1->TWI_QSPIx_STS, TWI_QSPIx_STS_DLUFIF)) {
        QSPI1->TWI_QSPIx_STS = 0x00000040;
        PC_OT(0);
        DL_OK = 1;
    }
  /*<Generated by EasyCodeCube begin>*/
#if  (TestNum == 3)
  QSPIx_1_3_FiFO_TFTDriver();
#endif
  /*<Generated by EasyCodeCube end>*/
  /*SPI1Interrupt Flag Clear begin*/
  //Forbid editing areas between the labels !!!
  /*SPI1Interrupt Flag Clear end*/
}

void DMA0_IRQHandler(void)
{
  /*DMA0_it write here begin*/
  //Forbid editing areas between the labels !!!
  /*DMA0_it write here*/
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
  /*DMA0Interrupt Flag Clear begin*/
  //Forbid editing areas between the labels !!!
  /*DMA0Interrupt Flag Clear end*/
}

void DMA1_IRQHandler(void)
{
  /*DMA1_it write here begin*/
  //Forbid editing areas between the labels !!!
  /*DMA1_it write here*/
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
  /*DMA1Interrupt Flag Clear begin*/
  //Forbid editing areas between the labels !!!
  /*DMA1Interrupt Flag Clear end*/
}

void DMA2_IRQHandler(void)
{
  /*DMA2_it write here begin*/
  //Forbid editing areas between the labels !!!
  /*DMA2_it write here*/
  /*<Generated by EasyCodeCube begin>*/ 
  /*<Generated by EasyCodeCube end>*/
  /*DMA2Interrupt Flag Clear begin*/
  //Forbid editing areas between the labels !!!
  /*DMA2Interrupt Flag Clear end*/
}

void DMA3_IRQHandler(void)
{
  /*DMA3_it write here begin*/
  //Forbid editing areas between the labels !!!
  /*DMA3_it write here*/
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
  /*DMA3Interrupt Flag Clear begin*/
  //Forbid editing areas between the labels !!!
  /*DMA3Interrupt Flag Clear end*/
}

void TIMER0_IRQHandler(void)
{
  /*TIM0_it write here begin*/
  //Forbid editing areas between the labels !!!
  /*TIM0_it write here*/
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
  /*TIMER0Interrupt Flag Clear begin*/
  //Forbid editing areas between the labels !!!
  /*TIMER0Interrupt Flag Clear end*/
	if(TIM_GetFlagStatus(TIM0, TIM_Flag_TI) == SET)
  {
    TIM_ClearFlag(TIM0, TIM_Flag_TI);
		lv_tick_inc(1);
  }
}

void TIMER1_IRQHandler(void)
{
  /*TIM1_it write here begin*/
  //Forbid editing areas between the labels !!!
  /*TIM1_it write here*/
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
  /*TIMER1Interrupt Flag Clear begin*/
  //Forbid editing areas between the labels !!!
  /*TIMER1Interrupt Flag Clear end*/
	if(TIM_GetFlagStatus(TIM0, TIM_Flag_TI) == SET)
  {
    TIM_ClearFlag(TIM0, TIM_Flag_TI);
		lv_tick_inc(1);
  }
}

void TIMER2_IRQHandler(void)
{
  /*TIM2_it write here begin*/
  //Forbid editing areas between the labels !!!
  /*TIM2_it write here*/
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
  /*TIMER2Interrupt Flag Clear begin*/
  //Forbid editing areas between the labels !!!
  /*TIMER2Interrupt Flag Clear end*/
}

void TIMER3_IRQHandler(void)
{
  /*TIM3_it write here begin*/
  //Forbid editing areas between the labels !!!
  /*TIM3_it write here*/
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
  /*TIMER3Interrupt Flag Clear begin*/
  //Forbid editing areas between the labels !!!
  /*TIMER3Interrupt Flag Clear end*/
}

void TIMER4_5_IRQHandler(void)
{
  /*TIM4_5_it write here begin*/
  //Forbid editing areas between the labels !!!
  /*TIM4_5_it write here*/
  /*<Generated by EasyCodeCube begin>*/ 
  /*<Generated by EasyCodeCube end>*/
  /*TIMER4_5Interrupt Flag Clear begin*/
  //Forbid editing areas between the labels !!!
  /*TIMER4_5Interrupt Flag Clear end*/
}

void TIMER6_7_IRQHandler(void)
{
  /*TIM6_7_it write here begin*/
  //Forbid editing areas between the labels !!!
  /*TIM6_7_it write here*/
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
  /*TIMER6_7Interrupt Flag Clear begin*/
  //Forbid editing areas between the labels !!!
  /*TIMER6_7Interrupt Flag Clear end*/
}

void PWM0_IRQHandler(void)
{
  /*PWM0_it write here begin*/
  //Forbid editing areas between the labels !!!
  /*PWM0_it write here*/
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
  /*PWM0Interrupt Flag Clear begin*/
  //Forbid editing areas between the labels !!!
  /*PWM0Interrupt Flag Clear end*/
}

void LEDPWM_IRQHandler(void)
{
  /*LEDPWM_it write here begin*/
  //Forbid editing areas between the labels !!!
  /*LEDPWM_it write here*/
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
  /*LEDPWMInterrupt Flag Clear begin*/
  //Forbid editing areas between the labels !!!
  /*LEDPWMInterrupt Flag Clear end*/
}



void ADC_IRQHandler(void)
{
  /*ADC_it write here begin*/
  //Forbid editing areas between the labels !!!
  /*ADC_it write here*/
  /*<Generated by EasyCodeCube begin>*/

  /*<Generated by EasyCodeCube end>*/
  /*ADCInterrupt Flag Clear begin*/
  //Forbid editing areas between the labels !!!
  /*ADCInterrupt Flag Clear end*/
}
void CAN_IRQHandler(void)
{
  /*CAN_it write here begin*/
  //Forbid editing areas between the labels !!!
  /*CAN_it write here*/
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
  /*CANInterrupt Flag Clear begin*/
  //Forbid editing areas between the labels !!!
  /*CANInterrupt Flag Clear end*/
}
void CMP_IRQHandler(void)
{
  /*CMP_it write here begin*/
  //Forbid editing areas between the labels !!!
  /*CMP_it write here*/
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
  /*CMPInterrupt Flag Clear begin*/
  //Forbid editing areas between the labels !!!
  /*CMPInterrupt Flag Clear end*/
}


void SysTick_IRQHandler(void)
{
  /*SysTick_it write here begin*/
  //Forbid editing areas between the labels !!!
  /*SysTick_it write here*/
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
  /*SysTickInterrupt Flag Clear begin*/
  //Forbid editing areas between the labels !!!
  /*SysTickInterrupt Flag Clear end*/
}

