/****************************************************************************
Copyright (c)  
FileName	   : SC_it.h
Author		   : 
Function	   : Interrupt service program header file
******************************************************************************
* @attention
*
*1.This software is supplied by SinOne Microelectronics Co.,Ltd. and is only 
*intended for use with SinOne products. No other uses are authorized. This 
*software is owned by SinOne Microelectronics Co.,Ltd. and is protected under 
*all applicable laws, including copyright laws. 
*2.The software which is for guidance only aims at providing customers with 
*coding information regarding their products in order for them to save time. 
*As a result, SinOne shall not be held liable for any direct, indirect or 
*consequential damages with respect to any claims arising from the content of 
*such software and/or the use made by customers of the coding information 
*contained herein in connection with their products.
*
*  COPYRIGHT 2024 SinOne Microelectronics
*/

#ifndef _SC_IT_H_
#define	_SC_IT_H_

#include "sc32_conf.h"

void INT0_IRQHandler(void);
void INT1_7_IRQHandler(void);
void INT8_11_IRQHandler(void);
void INT12_15_IRQHandler(void);
void RCC_IRQHandler(void);
#if !defined (TK_USE_BTM)
void BTM_IRQHandler(void);
#endif
void UART0_2_4_IRQHandler(void);
void UART1_3_5_IRQHandler(void);
void TWIx_QSPIx_1_3_IRQHandler(void);
void TWIx_QSPIx_0_2_IRQHandler(void);
void DMA0_IRQHandler(void);
void DMA1_IRQHandler(void);
void DMA2_IRQHandler(void);
void DMA3_IRQHandler(void);
void TIMER0_IRQHandler(void);
void TIMER1_IRQHandler(void);
void TIMER2_IRQHandler(void);
void TIMER3_IRQHandler(void);
void TIMER4_5_IRQHandler(void);
void TIMER6_7_IRQHandler(void);
void PWM0_IRQHandler(void);
void LEDPWM_IRQHandler(void);
void ADC_IRQHandler(void);
void CAN_IRQHandler(void);
void CMP_IRQHandler(void);
void SysTick_IRQHandler(void);
#endif


/**************************************Generated by EasyCodeCube*************************************/
//Forbid editing areas between the labels !!!
/*************************************.Generated by EasyCodeCube.************************************/
